apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: redis-vpa
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: redis-state
  updatePolicy:
    updateMode: "Auto" 
   
